### ISSUE TITLE
Add custom block registration

### ISSUE THREAD

**Issue by ianmcelvain** [cardinal-financial/glutenberg#6]
Test to make sure registering block types with @wordpress/components works.

**Comment by paulalexander-cf** [comment]
@ianmcelvain Here's the browser build index.js: https://gist.github.com/paulalexander-cf/6bf471d46157c4cebf50cd23489d6985

**Comment by ianmcelvain** [comment]
@paulalexander-cf 

I found some difficulties registering a block compared to how we used to do it. Since we were using the editors' version of `@wordpress/*` packages, we were essentially sharing the same Redux store so it "just worked".

Now that it's a module, using an outside `@wordpress/blocks` package to call `registerBlockType()` will result in two different data sets (app-level store and the IsolatedBlockEditor store) where the editor is only using what it initialized with. 

I am starting to write the logic for this after researching the topic. I will document the solution shortly.
